Repository data-apis/array-api-extra, pull requests merged in 2025-04, with the labels that each got.

#201 DEV: remove dependabot
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  .pre-commit-config.yaml
Labels: DX

#203 DEV: set dependency dashboard title
  renovate.json
Labels: DX

#209 DEV: tell renovate to ignore pinned deps
  renovate.json
Labels: dependencies, DX

#211 DEV: adjust renovate `rangeStrategy` and fix syntax
  renovate.json
Labels: dependencies, DX

#228 DEV: set some temporary renovate groups
  renovate.json
Labels: dependencies, DX

#237 DEV: iterate on renovate config
  renovate.json
Labels: dependencies, DX

#238 DEV: try to fix renovate config
  renovate.json
Labels: dependencies, DX

#253 DEV: address renovate config wishlist
  renovate.json
Labels: dependencies, DX

#262 MAINT: remove obsolete `docs/requirements.txt`
  docs/requirements.txt
Labels: maintenance

#221 TST: run tests on CPU+GPU
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_backends.py
  src/array_api_extra/_lib/_testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: testing

#263 DEV: add Pixi task descriptions
  pixi.lock
  pyproject.toml
Labels: DX

#265 MAINT: Don't use `Backend` for delegation
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/__init__.py
  src/array_api_extra/_lib/_backends.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: maintenance

#272 TST: flaky `test_single_axis` on Dask
  tests/test_funcs.py
Labels: testing

#276 DEV: disable codecov project status
  codecov.yml
Labels: DX

#281 deps: schedule hypothesis monthly
  renovate.json
Labels: dependencies

#288 deps: disable requires-python updates
  renovate.json
Labels: dependencies
