Repository data-apis/array-api-extra, pull requests merged in 2025-02, with the labels that each got.

#132 TST: `xfail_xp_backend`
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_testing.py
  tests/test_utils.py
Labels: testing

#138 DEV: Add editorconfig
  .editorconfig
Labels: DX

#133 ENH: `broadcast_shapes`
  docs/api-reference.md
  docs/conf.py
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_funcs.py
  tests/test_funcs.py
Labels: enhancement, new function

#143 BUG: `isclose` finite vs. infinite
  src/array_api_extra/_lib/_funcs.py
  tests/test_funcs.py
Labels: bug

#146 MAINT: various backports and tweaks
  docs/conf.py
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_utils/_helpers.py
  src/array_api_extra/_lib/_utils/_typing.py
  src/array_api_extra/testing.py
  tests/conftest.py
Labels: maintenance

#145 TST: refactor test_utils
  tests/test_helpers.py
  tests/test_utils.py
Labels: testing, maintenance

#148 REL: set version to 0.6.1
  pixi.lock
  src/array_api_extra/__init__.py
Labels: release

#137 ENH: `create_diagonal`: support broadcasting
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_utils/_helpers.py
  tests/test_funcs.py
  tests/test_helpers.py
Labels: enhancement

#135 BUG: `at` should not force overwrite in Dask when copy=None
  src/array_api_extra/_lib/_at.py
  tests/test_at.py
Labels: bug, lazy arrays
