Repository data-apis/array-api-extra, pull requests merged in 2025-01, with the labels that each got.

#75 DOC: update all-contributors
  .all-contributorsrc
  .gitignore
  CONTRIBUTORS.md
  README.md
Labels: documentation

#53 ENH: implement `at`
  .github/workflows/ci.yml
  docs/api-reference.md
  docs/conf.py
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_funcs.py
  src/array_api_extra/_lib/_compat.py
  src/array_api_extra/_lib/_compat.pyi
  src/array_api_extra/_lib/_typing.py
  tests/test_at.py
  vendor_tests/test_vendor.py
Labels: enhancement, new function

#81 DOC: clarify `at()` patterns/antipatterns
  src/array_api_extra/_funcs.py
Labels: documentation

#88 TST/BUG: run all tests on all backends; fix backend-specific bugs
  .pre-commit-config.yaml
  pixi.lock
  pyproject.toml
  src/array_api_extra/_funcs.py
  src/array_api_extra/_lib/_compat.py
  src/array_api_extra/_lib/_compat.pyi
  src/array_api_extra/_lib/_testing.py
  src/array_api_extra/_lib/_utils.py
  tests/__init__.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_testing.py
  tests/test_utils.py
  vendor_tests/test_vendor.py
Labels: bug, testing

#90 ENH: new function `nunique`
  docs/api-reference.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_funcs.py
  tests/test_funcs.py
Labels: enhancement, new function

#72 ENH: `pad`: add delegation
  docs/api-reference.md
  docs/index.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/__init__.py
  src/array_api_extra/_lib/_backends.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_testing.py
  src/array_api_extra/_lib/_utils/__init__.py
  src/array_api_extra/_lib/_utils/_compat.py
  src/array_api_extra/_lib/_utils/_compat.pyi
  src/array_api_extra/_lib/_utils/_helpers.py
  src/array_api_extra/_lib/_utils/_typing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_testing.py
  tests/test_utils.py
  vendor_tests/test_vendor.py
Labels: enhancement, delegation

#95 MAINT: JAX CUDA environment
  pixi.lock
  pyproject.toml
Labels: DX

#101 MAINT: various refactoring
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_funcs.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
Labels: maintenance

#102 MAINT: clean up `pyproject.toml`
  pixi.lock
  pyproject.toml
  tests/test_testing.py
Labels: maintenance

#103 DOC: contributor docs for delegation
  docs/contributing.md
Labels: documentation

#104 DEV: `pixi run lint` improvements
  .github/workflows/ci.yml
  docs/contributing.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_utils/_compat.py
  tests/conftest.py
  tests/test_at.py
Labels: DX

#105 TST: better pytest short summary info
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/_backends.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_testing.py
  tests/test_utils.py
Labels: DX, testing

#111 DOC: tweak all-contributors table
  .all-contributorsrc
  CONTRIBUTORS.md
  README.md
Labels: documentation

#114 ENH: `pad`: `pad_width` can be any sequence
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/_funcs.py
  tests/test_funcs.py
Labels: enhancement, API

#113 ENH: new function `isclose`
  docs/api-reference.md
  pixi.lock
  src/array_api_extra/__init__.py
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_testing.py
  tests/test_funcs.py
  tests/test_testing.py
Labels: enhancement, new function

#118 MAINT: Simplify `at` implementation
  src/array_api_extra/_lib/_at.py
Labels: maintenance

#123 MAINT: bump pixi to 0.40.3
  .github/workflows/ci.yml
  .github/workflows/docs-build.yml
  pixi.lock
Labels: maintenance

#115 ENH: Test tools for jax.jit and dask
  docs/index.md
  docs/testing-utils.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_testing.py
  src/array_api_extra/testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_testing.py
  tests/test_utils.py
Labels: enhancement, lazy arrays, xpx.testing

#121 ENH: `at` support for bool mask in Dask and JAX
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_utils/_compat.py
  src/array_api_extra/_lib/_utils/_compat.pyi
  tests/test_at.py
  vendor_tests/test_vendor.py
Labels: enhancement, lazy arrays

#127 BUG: vendored xpx.testing crashes on import
  src/array_api_extra/testing.py
  vendor_tests/test_vendor.py
Labels: bug, xpx.testing

#129 BUG: `setdiff1d` vs. non-1d arrays
  src/array_api_extra/_lib/_funcs.py
  tests/test_funcs.py
Labels: bug
