Repository data-apis/array-api-extra, pull requests merged in 2025-06, with the labels that each got.

#310 ENH: New function `default_dtype`
  docs/api-reference.md
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_funcs.py
  tests/conftest.py
  tests/test_funcs.py
Labels: enhancement, new function

#306 ENH: add new function `one_hot`
  docs/api-reference.md
  src/array_api_extra/__init__.py
  src/array_api_extra/_delegation.py
  src/array_api_extra/_lib/_funcs.py
  tests/test_funcs.py
Labels: enhancement, new function

#312 REL: prepare v0.8.0 release
  pixi.lock
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_utils/_helpers.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_testing.py
Labels: release

#330 ENH: Free-threading support
  .github/workflows/ci.yml
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_backends.py
  src/array_api_extra/_lib/_lazy.py
  src/array_api_extra/testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: enhancement
