Repository data-apis/array-api-extra, pull requests merged in 2025-03, with the labels that each got.

#120 MAINT: Upgrade to array-api-compat 1.11
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_utils/_compat.py
  src/array_api_extra/_lib/_utils/_compat.pyi
  tests/test_at.py
  tests/test_funcs.py
  vendor_tests/test_vendor.py
Labels: maintenance

#153 BUG: `lazy_xp_function` crashes with Cython ufuncs
  src/array_api_extra/testing.py
  tests/test_testing.py
Labels: bug, lazy arrays

#155 ENH: `lazy_xp_function` to materialize exceptions on Dask
  src/array_api_extra/testing.py
  tests/test_testing.py
Labels: enhancement, lazy arrays, xpx.testing

#157 MAINT: Allow `import xpx.testing` outside of test modules
  src/array_api_extra/testing.py
Labels: maintenance, xpx.testing

#158 ENH: `lazy_xp_function` namespaces support
  src/array_api_extra/testing.py
  tests/test_testing.py
Labels: enhancement, lazy arrays, xpx.testing

#159 TYP: Full annotations for Array objects
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_testing.py
  src/array_api_extra/_lib/_utils/_compat.pyi
  src/array_api_extra/_lib/_utils/_helpers.py
  src/array_api_extra/_lib/_utils/_typing.py
  src/array_api_extra/_lib/_utils/_typing.pyi
  src/array_api_extra/testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_testing.py
Labels: static typing

#162 TST: fix failures in `expand_dims` test
  tests/test_funcs.py
Labels: maintenance

#141 ENH: `apply_where` (migrate `lazywhere` from scipy)
  docs/api-reference.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_utils/_helpers.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
Labels: enhancement, new function

#86 ENH: `lazy_apply`
  docs/api-lazy.md
  docs/index.md
  docs/testing-utils.md
  pixi.lock
  pyproject.toml
  src/array_api_extra/__init__.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_lazy.py
  src/array_api_extra/_lib/_utils/_typing.pyi
  src/array_api_extra/testing.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: enhancement, new function, lazy arrays

#165 BUG: `isclose` PyTorch Array API 2024.12 compliance
  src/array_api_extra/_delegation.py
  tests/test_funcs.py
Labels: bug

#168 DOC: fix copyright
  docs/conf.py
Labels: documentation

#170 MAINT: drop Python 3.9 informal support
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_lazy.py
  src/array_api_extra/_lib/_utils/_helpers.py
  src/array_api_extra/testing.py
Labels: DX, static typing, maintenance

#171 MAINT: capitalization nits
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_lazy.py
  src/array_api_extra/testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: maintenance

#174 CI/MAINT: test vs. NumPy 1.22
  pixi.lock
  pyproject.toml
  tests/conftest.py
Labels: CI, testing, maintenance

#175 DOC: update README
  README.md
Labels: documentation

#176 MAINT: general deps bump
  pixi.lock
  pyproject.toml
  src/array_api_extra/_lib/_lazy.py
  src/array_api_extra/_lib/_testing.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_lazy.py
Labels: DX, maintenance

#182 DEV: Configure pixi for Intel Macs
  pixi.lock
  pyproject.toml
Labels: DX

#186 DEV: pin CUDA variant for PyTorch
  pixi.lock
  pyproject.toml
Labels: dependencies

#179 ENH/TST: tougher restrictions on array_api_strict
  src/array_api_extra/_lib/_at.py
  src/array_api_extra/_lib/_backends.py
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_utils/_helpers.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: enhancement, testing
