Repository data-apis/array-api-extra, pull requests merged in 2025-05, with the labels that each got.

#289 REL: prepare 0.7.2 release
  pixi.lock
  src/array_api_extra/__init__.py
Labels: release

#295 MAINT: test against Dask 2025.5
  pixi.lock
  pyproject.toml
Labels: dependencies, maintenance

#294 MAINT: `reshape` does not accept int
  src/array_api_extra/_lib/_funcs.py
Labels: maintenance

#284 ENH: `jax_autojit`
  src/array_api_extra/_lib/_utils/_helpers.py
  src/array_api_extra/testing.py
  tests/conftest.py
  tests/test_at.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: enhancement, lazy arrays, xpx.testing

#301 TST: rework tests for `xp_assert_equal`
  tests/test_testing.py
Labels: testing

#300 ENH: support PyTorch `device='meta'`
  src/array_api_extra/_lib/_funcs.py
  src/array_api_extra/_lib/_testing.py
  src/array_api_extra/_lib/_utils/_helpers.py
  tests/conftest.py
  tests/test_funcs.py
  tests/test_helpers.py
  tests/test_lazy.py
  tests/test_testing.py
Labels: enhancement
